### ISSUE TITLE
Azure Web App - Unable to find a config directory

### ISSUE THREAD

**Issue by afgallo** [HenrikJoreteg/getconfig#19]
I've deployed my app to azure and now am getting the following error:

Error: Unable to find a config directory
    at Object.internals.findConfig (D:\home\site\wwwroot\node_modules\getconfig\getconfig.js:44:15)
    at Object.internals.findConfig (D:\home\site\wwwroot\node_modules\getconfig\getconfig.js:47:22)
    at Object.internals.findConfig (D:\home\site\wwwroot\node_modules\getconfig\getconfig.js:47:22)
    at Object.internals.init (D:\home\site\wwwroot\node_modules\getconfig\getconfig.js:100:113)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\getconfig\getconfig.js:138:28)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

After looking at the source code, I am thinking the problem may lie in here:

`root = root || (require.main ? Path.dirname(require.main.filename) : process.cwd());`

If I set the **GETCONFIG_ROOT** env variable to 'wwwroot' I get a different error:

Error: No config files found
    at Object.internals.init (D:\home\site\wwwroot\node_modules\getconfig\getconfig.js:131:15)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\getconfig\getconfig.js:138:28)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:6:14)
    at Module._compile (module.js:398:26)

Any ideas?

**Comment by afgallo** [comment]
This has resolved the issue:

azure site config add SET GETCONFIG_ROOT=config

Still not sure why I had to set the root config folder to 'config'?
